### PR TITLE
Actions endpoint aware toolbar

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Comment by sneridagh** [comment]
Depends on merge of https://github.com/plone/plone.restapi/pull/514.

**Comment by tisto** [comment]
@sneridagh w00t! Awesome! Will try hard to find time to finish the actions endpoint. There are docs missing and the expansion...

**Comment by sneridagh** [comment]
@robgietema The actions endpoint is already merged.

**Comment by tisto** [comment]
@robgietema any chance we can merge this today? I'd like to present this on the Plone Tagung in Berlin tomorrow. :)

**Pull request merged**
