### PR TITLE
Switch to MIT license.

### PR DESCRIPTION
**Pull request by tisto**
As discussed with @polyester. React uses MIT.

### CODE REVIEW

**Comment by tisto** [comment]
@robgietema @jaroel @tareqalam @cekk @obct537 could you please briefly confirm that you are ok with moving the license from BSD-2 to MIT?

**Comment by jaroel** [comment]
Ack from me

**Comment by tisto** [comment]
@robgietema @tareqalam @cekk @obct537 can you please respond to this? We need to switch to MIT asap!

**Comment by cekk** [comment]
sorry, i thumbed up your previous comment ;)

So this means that's ok for me!

**Comment by tareqalam** [comment]
@tisto it's ok for me! thanks

**Comment by obct537** [comment]
Go for it

**Pull request merged**
